tempvenv: better error message when typoing the interpreter

diff --git a/bin/tempvenv b/bin/tempvenv
--- a/bin/tempvenv
+++ b/bin/tempvenv
@@ -11,7 +11,8 @@ if [ -n "${VIRTUAL_ENV:-}" ]; then
     exit 1
 fi
 
-python=$(command -v "${1:-python3}")
+py_name="${1:-python3}"
+python=$(command -v "$py_name") || { echo "Interpreter '$py_name' not in path"; exit 1; }
 venvdir="${XDG_CACHE_HOME:-$HOME/.cache}/tempvenv"
 
 mkdir -p "$venvdir"
@@ -26,7 +27,7 @@ trap 'rm -rf "$tmp"' EXIT
 virtualenv --quiet --python "$python" "$tmp" &>/dev/null || \
     "$python" -I -m venv "$tmp" &>/dev/null || \
     "$python" -m venv "$tmp" &>/dev/null || \
-    (echo "Failed to create venv with interpreter $python" && exit 1)
+    { echo "Failed to create venv with interpreter $python"; exit 1; }
 
 # Run a non-login shell that sources the venv
 $SHELL --rcfile <( echo "
